repos:
  - repo: https://github.com/awslabs/git-secrets      
    rev: v0.1.10 
    hooks: 
      - id: git-secrets
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: 1.3.0
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: shellcheck
      - id: gofmt
      - id: golint
